version: 3
services:
  go-shopping-demo:
    container_name: go-shopping-prod
    image: registry.cn-shanghai.aliyuncs.com/luckyziv/go-shopping-demo:0.0.2
    ports:
      - "3002:3002"
    environment:
      ENV: staging
    command: ./out
    depends_on:
      - mysql
      - redis
      - rabbitmq
  mysql:
    container_name: mysql-staging
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ziv
      MYSQL_USER: ziv
      MYSQL_PASSWORD: ziv
      MYSQL_DATABASE: go_shopping
    volumes:
      - "./mysql_data:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
networks:
  default:
    external:
      name: redis_default
