env: dev
version: 0.0.1
mysql:
  userName: root
  pass: ziv
  host: localhost
  port: 3306
  dbName: go_shopping
redis:
  addr: "localhost:6379"
  password: ziv
  db: 0
  sentinelMasterName: mymaster
  sentinelAddr:
    - :26379
    - :26380
    - :26381
amqp:
  userName: admin
  password: admin
  host: "localhost:5672"
elasticsearch:
  host: localhost
  port: 9201
logger:
  AppFilePath: "./logs/app"
  ApiFilePath: "./logs/api"
jwt:
  jwtKey: a_secret_key_zIv
  issuer: ziv
  subject: user_token
server:
  port: 3002
