env: dev
version: 0.0.1
mysql:
  userName: root
  pass: ziv
  host: localhost
  prot: 3306
  dbName: shopping
redis:
  addr: 'localhost:6379'
  password: ziv
  db: 0
  sentinelMasterName: mymaster
  sentinelAddr:
    - "26379"
    - "26380"
    - "26381"
amqp:
  userName: admin
  password: admin
  host: 'localhost:5672/'
server:
  port: 3002
