# 下面的host参数均为docker-compose.yml中的hostname
env: dev
version: 0.0.1
mysql:
  userName: root
  pass: ziv
  host: mysql-staging
  port: 3306
  dbName: go_shopping
redis:
  addr: "redis:6379"
  password: ziv
  db: 0
  sentinelMasterName: mymaster
  sentinelAddr:
    - "redis-sentinel-1:26379"
    - "redis-sentinel-1:26480"
    - "redis-sentinel-1:26481"
amqp:
  userName: admin
  password: admin
  host: "rabbitmq:5672"
amqpkey:
  orderDlxExchange: dlx_exchange
  orderDlxQueue: dlx_queue
  orderDlxRoutingKey: orders_auto_cancel
  orderExchange: orders_normal
  orderQueue: orders_queue
  orderRoutingKey: orders
elasticsearch:
  host: elasticsearch
  port: 9200
logger:
  AppFilePath: "./logs/app"
  ApiFilePath: "./logs/api"
jwt:
  jwtKey: a_secret_key_zIv
  issuer: ziv
  subject: user_token
server:
  port: 3002
